<a href="https://colab.research.google.com/github/Stamatics-NumberstoNeurons/assignment1-basicpythonandnumpy-nupur-sehgal/blob/main/numpy_worksheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Exercises — 50 Problems

**Instructions:**
- Run the first cell to import NumPy before starting.
- Each exercise has a **Question** and an **Input** (where given).
- Write your solution in the `# Write your code here:` cell below each question.
- Run your cell to check your output.
- Do **not** modify the Input cells or the import cell.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [2]:
# Run this cell before starting — do not modify
import numpy as np

## Section 1 — Array Basics (Exercises 1–10)

### Exercise 1 — NumPy Version

**Question:** Print the version of NumPy.


In [3]:
# Write your code here:
print(np.__version__)

2.0.2


### Exercise 2 — 1D Array

**Question:** Create a 1D array of numbers from 0 to 9.


In [4]:
# Write your code here:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Exercise 3 — Boolean Array

**Question:** Create a 3×3 NumPy array of all `True`s.


In [15]:
# Write your code here:
arr_1 = np.ones((3, 3), dtype=bool)
print(arr_1)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Exercise 4 — Filter Odd Numbers

**Question:** Extract all odd numbers from `arr`.


In [13]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# Write your code here:
print(arr[1::2])

[1 3 5 7 9]


### Exercise 5 — Replace In-Place

**Question:** Replace all odd numbers in `arr` with `-1`.


In [17]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Write your code here:
arr[1::2] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 6 — Replace Without Modifying Original

**Question:** Replace all odd numbers in `arr` with `-1` **without** changing the original array.


In [19]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# Write your code here:
new_arr=arr.copy()
new_arr[1::2] = -1
print("Original =",arr)
print("New =", new_arr)

Original = [0 1 2 3 4 5 6 7 8 9]
New = [ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 7 — Reshape Array

**Question:** Convert a 1D array to a 2D array with 2 rows.


In [23]:
# Input — do not modify
arr = np.arange(10)

In [24]:
# Write your code here:
new_arr=arr.reshape(2,5)
print(new_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Exercise 8 — Vertical Stack

**Question:** Stack arrays `a` and `b` vertically.


In [26]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [27]:
# Write your code here:
result = np.vstack((a, b))
print(result)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Exercise 9 — Horizontal Stack

**Question:** Stack arrays `a` and `b` horizontally.


In [28]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [29]:
# Write your code here:
result=np.hstack((a,b))
print(result)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Exercise 10 — Custom Sequence

**Question:** Create the following pattern **without hardcoding**. Use only NumPy functions and the input array `a`.

Expected output: `array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`


In [30]:
# Input — do not modify
a = np.array([1, 2, 3])

In [31]:
# Write your code here:
result = np.r_[np.repeat(a, 3), np.tile(a, 3)]
print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## Section 2 — Set Operations & Filtering (Exercises 11–19)

### Exercise 11 — Common Items

**Question:** Get the common items between arrays `a` and `b`.


In [32]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [33]:
# Write your code here:
common=np.intersect1d(a,b)
print(common)

[2 4]


### Exercise 12 — Remove Items

**Question:** From array `a`, remove all items present in array `b`.


In [36]:
# Input — do not modify
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [37]:
# Write your code here:
result=np.setdiff1d(a,b)
print(result)

[1 2 3 4]


### Exercise 13 — Matching Positions

**Question:** Get the positions where elements of `a` and `b` match.


In [40]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [41]:
# Write your code here:
positions=np.where(a==b)
print(positions)

(array([1, 3, 5, 7]),)


### Exercise 14 — Extract Range

**Question:** Get all items between 5 and 10 from array `a`.


In [42]:
# Input — do not modify
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [43]:
# Write your code here:
result = a[(a >= 5) & (a <= 10)]
print(result)

[ 6  9 10]


### Exercise 15 — Vectorize a Function

**Question:** Convert the scalar function `maxx` below to work on two arrays.


In [44]:
# Input — do not modify
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [45]:
# Write your code here:
result=np.vectorize(maxx)(a,b)
print(result)

[6 7 9 8 9 7 5]


### Exercise 16 — Swap Columns

**Question:** Swap columns 1 and 2 in array `arr`.


In [46]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [49]:
# Write your code here:
arr[:, [0, 1]] = arr[:, [1, 0]]
print(arr)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


### Exercise 17 — Swap Rows

**Question:** Swap rows 1 and 2 in array `arr`.


In [51]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [52]:
# Write your code here:
arr[[0,1], :] = arr[[1,0], :]
print(arr)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


### Exercise 18 — Reverse Rows

**Question:** Reverse the rows of the 2D array `arr`.


In [53]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [59]:
# Write your code here:
result = arr[::-1,:]
print(result)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


### Exercise 19 — Reverse Columns

**Question:** Reverse the columns of the 2D array `arr`.


In [55]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [58]:
# Write your code here:
result=arr[:, ::-1]
print(result)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


## Section 3 — Printing & Formatting (Exercises 20–24)

### Exercise 20 — Random Float Array

**Question:** Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.


In [60]:
# Write your code here:
arr=np.random.random((5,3))
arr=arr*5+5
print(arr)

[[6.09679303 7.67301002 8.59575886]
 [9.15842764 8.81962501 8.48341209]
 [6.81912656 7.30461878 5.92715775]
 [8.75400048 8.10666291 6.86117558]
 [6.98182402 8.58123195 5.01880129]]


### Exercise 21 — Decimal Places

**Question:** Print only 3 decimal places of the array `rand_arr`.


In [61]:
# Input — do not modify
rand_arr = np.random.random((5,3))

In [62]:
# Write your code here:
print(np.around(rand_arr,3))

[[0.515 0.403 0.311]
 [0.869 0.553 0.242]
 [0.84  0.327 0.446]
 [0.597 0.973 0.916]
 [0.466 0.167 0.13 ]]


### Exercise 22 — Suppress Scientific Notation

**Question:** Pretty print `rand_arr` by suppressing scientific notation (like `1e10`).


In [63]:
# Input — do not modify
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [64]:
# Write your code here:
np.set_printoptions(suppress=True)
print(rand_arr)

[[0.0005434  0.00027837 0.00042452]
 [0.00084478 0.00000472 0.00012157]
 [0.00067075 0.00082585 0.00013671]]


### Exercise 23 — Limit Print Output

**Question:** Limit the number of items printed in array `a` to a maximum of 6 elements.


In [67]:
# Input — do not modify
a = np.arange(15)

In [68]:
# Write your code here:
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


### Exercise 24 — Print Full Array

**Question:** Print the full NumPy array `a` without truncating.


In [70]:
# Input — do not modify
np.set_printoptions(threshold=6)
a = np.arange(15)

In [71]:
# Write your code here:
np.set_printoptions(threshold=np.inf)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Section 4 — Iris Dataset (Exercises 25–46)

### Exercise 25 — Import Dataset

**Question:** Import the Iris dataset keeping the text intact.

> URL: `https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv`


In [129]:
# Write your code here:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
iris_data = np.genfromtxt(url, delimiter=',', dtype='object')
print(iris_data[:3])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']]


### Exercise 26 — Extract Text Column

**Question:** Extract the text column `species` from the 1D iris dataset imported in Exercise 25.

*# Make sure you have run Exercise 25 first so that iris_data is defined.*


In [130]:
# Write your code here:
species = iris_data[:, 4]
print(species[:5])

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


### Exercise 27 — 1D to 2D Array

**Question:** Convert the 1D iris dataset to a 2D array `iris_2d` by omitting the species text field.

*# Make sure you have run Exercise 25 first.*


In [138]:
# Write your code here:
iris_2d = iris_data[:, :4].astype('float')
print(iris_2d[:3])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]


### Exercise 28 — Mean, Median, Std

**Question:** Find the mean, median, and standard deviation of the sepal length (1st column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [136]:
# Write your code here:
sepal_length = iris_2d[:, 0].astype(float)

print(np.mean(sepal_length))
print(np.median(sepal_length))
print(np.std(sepal_length))


5.843333333333334
5.8
0.8253012917851409


### Exercise 29 — Normalize Array

**Question:** Create a normalized form of iris's sepal length whose values range exactly between 0 and 1 (minimum → 0, maximum → 1).

*# Make sure you have run Exercise 27 first.*


In [137]:
# Write your code here:
sepal_len = iris_2d[:, 0]
normalized = (sepal_len - sepal_len.min()) / (sepal_len.max() - sepal_len.min())
print(normalized[:5])

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444]


### Exercise 30 — Softmax Score

**Question:** Compute the softmax score of the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [135]:
# Write your code here:
sepal_len = iris_2d[:, 0]
exp_vals = np.exp(sepal_len - sepal_len.max())
softmax = exp_vals / exp_vals.sum()
print(softmax[:5])

[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836]


### Exercise 31 — Percentile Scores

**Question:** Find the 5th and 95th percentile of iris's sepal length.

*# Make sure you have run Exercise 27 first.*


In [85]:
# Write your code here:
sepal_len = iris_2d[:, 0]
print('5th percentile:', np.percentile(sepal_len, 5))
print('95th percentile:', np.percentile(sepal_len, 95))

5th percentile: 4.6
95th percentile: 7.254999999999998


### Exercise 32 — Insert Missing Values

**Question:** Insert `np.nan` values at 20 random positions in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [86]:
# Write your code here:
np.random.seed(42)
iris_2d = iris_2d.copy()
i = np.random.randint(0, iris_2d.shape[0], 20)
j = np.random.randint(0, iris_2d.shape[1], 20)
iris_2d[i, j] = np.nan
print(iris_2d[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 nan]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Exercise 33 — Find Missing Values

**Question:** Find the **number** and **position** of missing values in `iris_2d`'s sepal length (1st column).

*# Make sure you have run Exercise 32 first.*


In [87]:
# Write your code here:
col = iris_2d[:, 0]
print('Number of NaNs:', np.sum(np.isnan(col)))
print('Positions:', np.argwhere(np.isnan(col)).flatten())

Number of NaNs: 5
Positions: [ 14  87 106 116 121]


### Exercise 34 — Multi-Condition Filter

**Question:** Filter the rows of `iris_2d` that have:
- petal length (3rd column) > 1.5, **and**
- sepal length (1st column) < 5.0

*# Make sure you have run Exercise 32 first.*


In [88]:
# Write your code here:
mask = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
print(iris_2d[mask])

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]]


### Exercise 35 — Drop Rows with NaN

**Question:** Select rows of `iris_2d` that do **not** have any `nan` value.

*# Make sure you have run Exercise 32 first.*


In [89]:
# Write your code here:
no_nan_rows = iris_2d[~np.any(np.isnan(iris_2d), axis=1)]
print(no_nan_rows[:5])

[[5.1 3.5 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]


### Exercise 36 — Correlation

**Question:** Find the correlation between sepal length (1st column) and petal length (3rd column) in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [157]:
# Write your code here:
corr = np.corrcoef(iris_2d[:, 0], iris_2d[:, 2])[0, 1]
print('Correlation:', corr)

Correlation: 0.8717541573048718


### Exercise 37 — Check for NaN

**Question:** Find out if `iris_2d` has any missing values.

*# Make sure you have run Exercise 32 first.*


In [156]:
# Write your code here:
print('Has NaN:', np.isnan(iris_2d).any())

Has NaN: False


### Exercise 38 — Replace NaN with 0

**Question:** Replace all occurrences of `nan` with `0` in `iris_2d`.

*# Make sure you have run Exercise 32 first.*


In [155]:
# Write your code here:
iris_2d[np.isnan(iris_2d)] = 0
print(iris_2d[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### Exercise 39 — Unique Value Counts

**Question:** Find the unique values and their counts in iris's species column.

*# Make sure you have run Exercise 25 first.*


In [154]:
# Write your code here:
values, counts = np.unique(species, return_counts=True)
for v, c in zip(values, counts):
    print(v, ':', c)

b'Iris-setosa' : 50
b'Iris-versicolor' : 50
b'Iris-virginica' : 50


### Exercise 40 — Numeric to Categorical

**Question:** Bin the petal length (3rd column) of `iris_2d` to form a text array using these rules:
- `< 3` → `'small'`
- `3–5` → `'medium'`
- `>= 5` → `'large'`

*# Make sure you have run Exercise 27 first.*


In [153]:
# Write your code here:
petal_len = iris_2d[:, 2]
bins = np.digitize(petal_len, bins=[0, 3, 5])
labels = np.array(['small', 'medium', 'large'])
categories = labels[bins - 1]
print(categories[:10])

['small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small']


### Exercise 41 — Create New Column

**Question:** Create a new column for **volume** in `iris_2d`, where:

> volume = (π × petal_length × sepal_length²) / 3

*# Make sure you have run Exercise 27 first.*


In [152]:
# Write your code here:
volume = (np.pi * iris_2d[:, 2] * iris_2d[:, 0]**2) / 3
iris_2d_with_vol = np.column_stack([iris_2d, volume])
print(iris_2d_with_vol[:3])

[[ 5.1         3.5         1.4         0.2        38.13265163]
 [ 4.9         3.          1.4         0.2        35.20049849]
 [ 4.7         3.2         1.3         0.2        30.07237208]]


### Exercise 42 — Probabilistic Sampling

**Question:** Randomly sample iris's species such that **setosa** appears **twice** as often as versicolor and virginica.

*# Make sure you have run Exercise 25 first.*


In [151]:
# Write your code here:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
iris_data_clean = np.genfromtxt(url, delimiter=',', dtype='object')
species_all = iris_data_clean[:, 4]

# Assign weights: setosa=2, others=1
probs = np.where(species_all == b'Iris-setosa', 2, 1).astype(float)
probs /= probs.sum()

sampled = np.random.choice(species_all, size=100, replace=True, p=probs)
vals, counts = np.unique(sampled, return_counts=True)
for v, c in zip(vals, counts):
    print(v, ':', c)

b'Iris-setosa' : 50
b'Iris-versicolor' : 27
b'Iris-virginica' : 23


### Exercise 43 — Second Largest Value

**Question:** Find the **second longest** petal length among iris samples of species **setosa**.

*# Make sure you have run Exercise 25 first.*


In [150]:
# Write your code here:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
iris_raw = np.genfromtxt(url, delimiter=',', dtype='object')
setosa_mask = iris_raw[:, 4] == b'Iris-setosa'
setosa_petal = iris_raw[setosa_mask, 2].astype(float)
sorted_petal = np.sort(setosa_petal)
print('Second longest petal length in setosa:', sorted_petal[-2])

Second longest petal length in setosa: 1.9


### Exercise 44 — Sort 2D Array by Column

**Question:** Sort the iris dataset based on the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [149]:
# Write your code here:
idx = np.argsort(iris_2d[:, 0])
print(iris_2d[idx][:5])

[[4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]]


### Exercise 45 — Most Frequent Value

**Question:** Find the most frequent value of petal length (3rd column) in the iris dataset.

*# Make sure you have run Exercise 27 first.*


In [148]:
# Write your code here:
petal_len = iris_2d[:, 2]
vals, counts = np.unique(petal_len, return_counts=True)
print('Most frequent petal length:', vals[np.argmax(counts)])

Most frequent petal length: 1.5


### Exercise 46 — First Value Greater Than

**Question:** Find the position of the **first occurrence** of a value greater than 1.0 in the petal width (4th column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [147]:
# Write your code here:
petal_width = iris_2d[:, 3]
print('First position > 1.0:', np.argwhere(petal_width > 1.0)[0, 0])

First position > 1.0: 50


## Section 5 — Miscellaneous (Exercises 47–50)

### Exercise 47 — Clip Values

**Question:** From array `a`, replace all values **greater than 30** with `30`, and all values **less than 10** with `10`.


In [139]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [140]:
# Write your code here:
print(np.clip(a, 10, 30))

[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


### Exercise 48 — Top N Positions

**Question:** Get the positions of the **top 5 maximum values** in array `a`.


In [141]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [142]:
# Write your code here:
print(np.argsort(a)[-5:][::-1])

[15 10  3  7 18]


### Exercise 49 — Row-wise Unique Counts

**Question:** Compute the counts of unique values **row-wise** in the input array.


In [143]:
# Input — do not modify
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))

In [144]:
# Write your code here:
[np.unique(row, return_counts=True) for row in arr]
for i, row in enumerate(arr):
    vals, counts = np.unique(row, return_counts=True)
    print(f'Row {i}:', dict(zip(vals, counts)))

Row 0: {np.int64(1): np.int64(1), np.int64(3): np.int64(2), np.int64(4): np.int64(1), np.int64(5): np.int64(1), np.int64(6): np.int64(1), np.int64(8): np.int64(2), np.int64(9): np.int64(2)}
Row 1: {np.int64(1): np.int64(2), np.int64(2): np.int64(1), np.int64(3): np.int64(3), np.int64(5): np.int64(1), np.int64(7): np.int64(1), np.int64(9): np.int64(1), np.int64(10): np.int64(1)}
Row 2: {np.int64(2): np.int64(3), np.int64(4): np.int64(2), np.int64(5): np.int64(3), np.int64(6): np.int64(1), np.int64(8): np.int64(1)}
Row 3: {np.int64(1): np.int64(1), np.int64(3): np.int64(2), np.int64(4): np.int64(1), np.int64(6): np.int64(1), np.int64(8): np.int64(2), np.int64(9): np.int64(1), np.int64(10): np.int64(2)}
Row 4: {np.int64(1): np.int64(2), np.int64(2): np.int64(2), np.int64(3): np.int64(2), np.int64(6): np.int64(1), np.int64(7): np.int64(1), np.int64(8): np.int64(1), np.int64(9): np.int64(1)}
Row 5: {np.int64(1): np.int64(1), np.int64(2): np.int64(1), np.int64(3): np.int64(1), np.int64(4): n

### Exercise 50 — Flatten Array of Arrays

**Question:** Convert `arr_2d` (an array of arrays) into a flat 1D array.


In [145]:
# Input — do not modify
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)
arr_2d = np.array([arr1, arr2, arr3], dtype=object)

In [146]:
# Write your code here:
print(np.concatenate(arr_2d))

[0 1 2 3 4 5 6 7 8 9]


---

## 🎉 Well done!

You've completed all 50 exercises. Review any exercises you found tricky and revisit the NumPy documentation for deeper understanding.